package com.joblens.api.common.domain;

import jakarta.persistence.Column;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import jakarta.persistence.Version;
import org.hibernate.annotations.UuidGenerator;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.Instant;
import java.util.UUID;

/**
 * Fields every persistent entity in JobLens shares.
 *
 * <p>This is a mapped superclass, not a table and not a business entity: it
 * exists so that companies, jobs, users and everything after them get an
 * identifier, audit timestamps and optimistic locking without each module
 * re-deciding how to do it.
 *
 * <h2>Identity: time-ordered UUID</h2>
 *
 * <p>Ids are UUIDs generated by the application, stored in PostgreSQL's native
 * {@code uuid} type (16 bytes, not a 36-character string).
 *
 * <p>The reason is that ids are public. They appear in URLs such as
 * {@code /api/v1/companies/{id}}, so a sequential {@code bigint} would tell any
 * caller how many companies exist and let them walk the whole table by counting
 * upwards. A UUID cannot be guessed or enumerated. It also means an id exists
 * before the row does, which the scan flow will need in order to reference a
 * company it is still resolving.
 *
 * <p>The cost is real and accepted: 16 bytes instead of 8, in the primary key
 * and in every future foreign key. What makes it affordable is
 * {@link UuidGenerator.Style#TIME} -- a time-ordered UUID. Random (version 4)
 * UUIDs scatter inserts across the whole B-tree, so every insert dirties a
 * different page and the index fragments. Time-ordered values append to the
 * right-hand edge of the index the way a sequence does, which keeps insert
 * performance close to a {@code bigint} and the index compact.
 *
 * <p>A UUID is not a friendly URL, which is why {@code Company} also carries a
 * slug. The two identifiers have different jobs: the UUID is the stable
 * primary key, the slug is the human-readable one.
 *
 * <h2>Timestamps</h2>
 *
 * <p>{@link Instant}, stored as {@code timestamptz}, always UTC. An
 * {@code Instant} is a moment on the timeline with no time zone of its own, so
 * it cannot be accidentally interpreted as local time. The database server's
 * time zone, the container's and the developer's laptop's all differ; none of
 * them is allowed to influence a stored value. Formatting into a user's time
 * zone is the frontend's job.
 *
 * <p>Timestamps are maintained by Spring Data auditing (see {@code JpaConfig})
 * rather than by database triggers or by hand, so a service cannot forget one
 * and cannot fake one.
 *
 * <h2>Version</h2>
 *
 * <p>Optimistic locking. Two concurrent updates to the same row fail loudly
 * instead of silently overwriting each other, which matters once tracking and
 * matching write on a user's behalf.
 *
 * <p>Columns are declared here, but Flyway still owns the actual schema;
 * {@code ddl-auto: validate} fails startup if the two ever disagree.
 */
@MappedSuperclass
@EntityListeners(AuditingEntityListener.class)
public abstract class BaseEntity {

    @Id
    @UuidGenerator(style = UuidGenerator.Style.TIME)
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    @Version
    @Column(name = "version", nullable = false)
    private long version;

    public UUID getId() {
        return id;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }

    public long getVersion() {
        return version;
    }

    /**
     * Entities are equal only when both have an id and it is the same id.
     * An entity without one is equal to nothing but itself.
     */
    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof BaseEntity that) || !getClass().isInstance(other)) {
            return false;
        }
        return id != null && id.equals(that.id);
    }

    /**
     * Deliberately constant per type. An id-based hash code would change when
     * the entity is persisted, losing it inside any hash-based collection it had
     * already been added to.
     */
    @Override
    public int hashCode() {
        return getClass().hashCode();
    }

    @Override
    public String toString() {
        return "%s{id=%s}".formatted(getClass().getSimpleName(), id);
    }
}
