-- The first real business table.
--
-- Other domains will point at this one -- jobs belong to a company, tracking
-- follows a company, a scan resolves to a company -- so the shape here is worth
-- getting right before anything references it.
--
-- Conventions established by this migration and followed by every later one:
--   * primary keys are UUID, generated by the application (see BaseEntity)
--   * timestamps are timestamptz and always UTC
--   * every table carries created_at, updated_at and version
--   * lengths are declared, because "unbounded text from an HTTP request" is
--     how a database fills up

CREATE TABLE companies (
    id              UUID          PRIMARY KEY,

    -- What a human typed, preserved exactly as given for display.
    name            VARCHAR(200)  NOT NULL,

    -- Deterministically derived from name: NFKC, diacritics stripped,
    -- lowercased, non-alphanumerics removed, whitespace collapsed.
    -- This is what duplicate detection and search actually compare, which is
    -- why it is unique rather than name.
    normalized_name VARCHAR(200)  NOT NULL,

    -- Stable, human-readable public identifier for URLs. Assigned at creation
    -- and never changed, so a link keeps working after a company is renamed.
    -- Slightly longer than name to leave room for a "-2" disambiguating suffix.
    slug            VARCHAR(220)  NOT NULL,

    description     VARCHAR(2000),
    website_url     VARCHAR(500),
    careers_url     VARCHAR(500),
    logo_url        VARCHAR(500),
    industry        VARCHAR(120),

    -- Free text for V1 ("Pune, India"). Structured location -- country, city,
    -- coordinates -- is a later concern and gets its own migration when a
    -- feature actually needs to filter on it.
    location        VARCHAR(200),

    -- Soft-availability flag, not a soft delete. A company hidden from search
    -- still keeps its jobs, its tracking rows and its scan history intact.
    active          BOOLEAN       NOT NULL DEFAULT TRUE,

    created_at      TIMESTAMPTZ   NOT NULL,
    updated_at      TIMESTAMPTZ   NOT NULL,
    version         BIGINT        NOT NULL DEFAULT 0,

    -- Cheap guards against data that is technically a string but useless.
    CONSTRAINT ck_companies_name_not_blank
        CHECK (length(btrim(name)) > 0),
    CONSTRAINT ck_companies_normalized_name_not_blank
        CHECK (length(btrim(normalized_name)) > 0)
);

-- Duplicate detection. The application checks for an existing normalized name
-- before inserting, but that check and the insert are not atomic: two
-- simultaneous requests can both pass it. This constraint is what actually
-- prevents the duplicate, and the service translates the resulting violation
-- into 409 Conflict.
CREATE UNIQUE INDEX ux_companies_normalized_name ON companies (normalized_name);

-- Slugs address a single company, so they must be unique. Also serves lookups
-- by slug.
CREATE UNIQUE INDEX ux_companies_slug ON companies (slug);

-- No index on `active` on purpose. A boolean has two values, so an index on it
-- cannot narrow the search enough to beat a scan, and PostgreSQL would usually
-- ignore it. If filtering by active ever becomes the bottleneck, the answer is
-- a partial index on the columns actually being searched, added then.
--
-- Note also that the current search is `normalized_name LIKE '%term%'`, which
-- no B-tree index can serve. That is a deliberate V1 trade-off: correct,
-- simple, and fine for the number of companies we will have. Step 6 revisits it
-- with pg_trgm and a GIN index, which is the real fix and needs an extension.

COMMENT ON TABLE  companies IS 'Companies discovered by JobLens, from a scan or entered directly.';
COMMENT ON COLUMN companies.normalized_name IS 'Derived from name; used for duplicate detection and search. Never set directly by a client.';
COMMENT ON COLUMN companies.slug IS 'Stable URL identifier. Assigned once at creation and never regenerated.';
COMMENT ON COLUMN companies.active IS 'Whether the company is shown in search. Not a delete flag.';
