-- Companies a user has chosen to follow.
--
-- One row per (user, company) pair. Follows the conventions of V2-V6: UUID
-- primary key generated by the application, timestamptz audit columns, and a
-- version column for optimistic locking, because every entity extends
-- BaseEntity and `ddl-auto: validate` requires the columns to exist.

CREATE TABLE tracked_companies (
    id          UUID        PRIMARY KEY,

    -- CASCADE on both sides, deliberately, and the opposite of what jobs do.
    --
    -- A tracking row is a preference *about* two other things. It has no
    -- meaning once either is gone: an account that is deleted takes its
    -- preferences with it, and a company that no longer exists cannot be
    -- followed. Compare jobs.company_id, which is RESTRICT because a job is
    -- real data in its own right and silently destroying it would be a loss.
    -- Here, keeping the row would only leave an orphan.
    --
    -- (Companies have no delete endpoint today, so the company side of this
    -- is about what the schema means rather than a path that currently runs.)
    user_id     UUID        NOT NULL REFERENCES users (id)     ON DELETE CASCADE,
    company_id  UUID        NOT NULL REFERENCES companies (id) ON DELETE CASCADE,

    -- created_at doubles as "tracked at". A separate column would hold the same
    -- value and could drift from it.
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL,
    version     BIGINT      NOT NULL DEFAULT 0,

    -- The rule this whole feature rests on: one user, one company, one row.
    --
    -- Enforced here rather than only in application code, because an
    -- application check followed by an insert is not atomic. Two requests from
    -- a double-click can both see "not tracked" and both insert; only the
    -- database can settle that, and TrackingService turns the losing insert
    -- into the same successful response the winner got.
    CONSTRAINT uq_tracked_companies_user_company UNIQUE (user_id, company_id)
);

-- The unique constraint above already creates a B-tree index on
-- (user_id, company_id). Because user_id is its leading column, that index
-- also serves every "companies this user tracks" lookup -- the listing, the
-- status check, the untrack -- so there is no separate index on user_id.
--
-- company_id is not the leading column of anything, so it gets its own index.
-- It is needed by the foreign key: without it, a cascading delete of a company
-- (or a future "how many people track this company" count) would scan the
-- whole table.
CREATE INDEX ix_tracked_companies_company_id ON tracked_companies (company_id);

-- Deliberately not indexed: (user_id, created_at) for the "most recently
-- tracked first" sort. A user tracks tens of companies, not thousands; once
-- the unique index has found their rows, sorting a few dozen in memory costs
-- nothing. An index here would be paid for on every insert to save
-- microseconds on reads. Revisit if a user ever tracks enough to make that
-- untrue.

COMMENT ON TABLE  tracked_companies IS 'Companies a user follows. One row per user and company.';
COMMENT ON COLUMN tracked_companies.created_at IS 'When the user started tracking the company; exposed as trackedAt.';
